name: 'jvds_sudoku_dart'
version: 0.0.1
description: A simple Sudoku solver implemented in Dart
author: Jan van de Sandt <jvdsandt@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.2.0 <2.0.0'

#dependencies:

dev_dependencies:
  test: ^0.12.0
